#!/usr/bin/env bash

set -euo pipefail

# =============================================================================
# STEP 19.2
#
# Combine the per-sample statistics generated by step 19.1 into one TSV table.
#
# Required files for every sample:
#   <sample>_genomicregions1k.txt
#   <sample>_IntronCvsL.txt
#
# Input directory:
#   data/clean/<PROJECT>_annotation_stats/
#
# Output:
#   data/clean/<PROJECT>_Table_genome_prediction_stats.tsv
#
# Usage:
#   bash scripts/3-POST-BRAKER/\
#19.2-parsing_extract_regions_output2.sh [PROJECT]
#
# Example:
#   bash scripts/3-POST-BRAKER/\
#19.2-parsing_extract_regions_output2.sh coass_revisit
#
# By default, the script exits with an error if any sample is missing.
# To intentionally generate a partial table:
#
#   ALLOW_MISSING=1 bash scripts/3-POST-BRAKER/\
#19.2-parsing_extract_regions_output2.sh coass_revisit
# =============================================================================

W="${1:-coass_revisit}"

# Locate the repository independently of the current working directory.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

# -----------------------------------------------------------------------------
# Input and output paths
# -----------------------------------------------------------------------------

SPECIES_LIST="${SPECIES_LIST:-${REPO_ROOT}/data/clean/names_${W}.txt}"

STATS_DIR="${STATS_DIR:-${REPO_ROOT}/data/clean/${W}_annotation_stats}"

OUTFILE="${OUTFILE:-${REPO_ROOT}/data/clean/${W}_Table_genome_prediction_stats.tsv}"

ALLOW_MISSING="${ALLOW_MISSING:-0}"

# -----------------------------------------------------------------------------
# Check inputs
# -----------------------------------------------------------------------------

[[ -f "$SPECIES_LIST" ]] || {
    echo "ERROR: species list not found: $SPECIES_LIST" >&2
    exit 1
}

[[ -d "$STATS_DIR" ]] || {
    echo "ERROR: statistics directory not found: $STATS_DIR" >&2
    exit 1
}

mkdir -p "$(dirname -- "$OUTFILE")"

# Work in a temporary directory and replace the final table only after the
# complete parsing step has finished.
tmp_dir="$(mktemp -d)"
trap 'rm -rf -- "$tmp_dir"' EXIT

tmp_out="${tmp_dir}/combined_annotation_stats.tsv"

# -----------------------------------------------------------------------------
# Write table header
# -----------------------------------------------------------------------------

printf '%s\n' \
    $'Species\tExonic\tIntronic\tUTR\tIntergenic\tLength_Genome\tProteins_predicted\tIntron_count_median\tIntron_count9thdecile\tIntron_Length\tCDS_length\tGene_density_per_100Kb_genome\tIntron_density_per_Kb_of_CDS' \
    > "$tmp_out"

processed=0
skipped=0

# -----------------------------------------------------------------------------
# Extract one row per sample
# -----------------------------------------------------------------------------

while IFS= read -r sample || [[ -n "$sample" ]]; do

    sample="${sample%$'\r'}"

    # Skip blank lines and comments.
    [[ -z "$sample" || "$sample" == \#* ]] && continue

    sample_dir="${STATS_DIR}/${sample}"

    regions_file="${sample_dir}/${sample}_genomicregions1k.txt"
    intron_file="${sample_dir}/${sample}_IntronCvsL.txt"

    echo "Collecting: $sample"

    if [[ ! -s "$regions_file" ]]; then
        echo "WARNING: missing or empty file: $regions_file" >&2
        ((skipped += 1))
        continue
    fi

    if [[ ! -s "$intron_file" ]]; then
        echo "WARNING: missing or empty file: $intron_file" >&2
        ((skipped += 1))
        continue
    fi

    # -------------------------------------------------------------------------
    # Extract genomic-region lengths
    #
    # Values are retrieved by region name instead of assuming that the rows are
    # always presented in exactly the same order.
    # -------------------------------------------------------------------------

    if ! region_values="$(
        awk -F '\t' '
            BEGIN {
                OFS = "\t"
            }

            NR > 1 {
                region = $2
                value  = $3

                # write.table() may surround text fields with quotes.
                gsub(/^"|"$/, "", region)
                gsub(/^"|"$/, "", value)

                values[region] = value
            }

            END {
                names[1] = "Exonic"
                names[2] = "Intronic"
                names[3] = "UTR"
                names[4] = "Intergenic"

                for (i = 1; i <= 4; i++) {
                    if (!(names[i] in values) || values[names[i]] == "") {
                        exit 2
                    }

                    printf "%s%s", values[names[i]], (i < 4 ? OFS : ORS)
                }
            }
        ' "$regions_file"
    )"; then
        echo "WARNING: invalid genomic-region table for $sample" >&2
        ((skipped += 1))
        continue
    fi

    # -------------------------------------------------------------------------
    # Extract the annotation and intron statistics
    #
    # Column 1 of this file is the sample name, which we already have.
    # Therefore, only columns 2-9 are retained.
    # -------------------------------------------------------------------------

    if ! intron_values="$(
        awk -F '\t' '
            BEGIN {
                OFS = "\t"
            }

            NR > 1 && NF >= 9 {
                for (i = 2; i <= 9; i++) {
                    gsub(/^"|"$/, "", $i)
                    values[i] = $i
                }

                found = 1
            }

            END {
                if (!found) {
                    exit 2
                }

                for (i = 2; i <= 9; i++) {
                    printf "%s%s", values[i], (i < 9 ? OFS : ORS)
                }
            }
        ' "$intron_file"
    )"; then
        echo "WARNING: invalid intron-summary table for $sample" >&2
        ((skipped += 1))
        continue
    fi

    printf '%s\t%s\t%s\n' \
        "$sample" \
        "$region_values" \
        "$intron_values" \
        >> "$tmp_out"

    ((processed += 1))

done < "$SPECIES_LIST"

# -----------------------------------------------------------------------------
# Validate and save final table
# -----------------------------------------------------------------------------

if ((processed == 0)); then
    echo "ERROR: no valid samples were found." >&2
    exit 1
fi

mv -- "$tmp_out" "$OUTFILE"

echo
echo "============================================================"
echo "STEP 19.2 SUMMARY"
echo "============================================================"
echo "Samples included: $processed"
echo "Samples skipped:  $skipped"
echo "Output table:     $OUTFILE"

if ((skipped > 0)) && [[ "$ALLOW_MISSING" != "1" ]]; then
    echo "ERROR: some samples were skipped." >&2
    echo "Fix the missing outputs or use ALLOW_MISSING=1 intentionally." >&2
    exit 1
fi

echo "Step 19.2 completed successfully."
