#!/usr/bin/env Rscript

# =============================================================================
# STEP 21.3
#
# Convert the genomic-region lengths generated by step 21.2 into percentages.
#
# Input:
#   data/clean/<PROJECT>_Table_genome_prediction_stats.tsv
#
# Output:
#   data/clean/<PROJECT>_percent_genome_annotation.tsv
#
# Usage:
#   Rscript scripts/3-POST-BRAKER/21.3-extract_percentages.R [PROJECT]
#
# Example:
#   Rscript scripts/3-POST-BRAKER/21.3-extract_percentages.R coass_revisit
#
# Custom input and output paths can also be provided:
#
#   Rscript scripts/3-POST-BRAKER/21.3-extract_percentages.R \
#       coass_revisit \
#       input_stats.tsv \
#       output_percentages.tsv
# =============================================================================

args <- commandArgs(trailingOnly = TRUE)

if (length(args) > 3) {
  stop(
    paste0(
      "Usage:\n",
      "  Rscript 21.3-extract_percentages.R [PROJECT]\n",
      "  Rscript 21.3-extract_percentages.R ",
      "PROJECT [INPUT_FILE] [OUTPUT_FILE]"
    ),
    call. = FALSE
  )
}

project <- if (length(args) >= 1) {
  args[[1]]
} else {
  "coass_revisit"
}

# -----------------------------------------------------------------------------
# Locate the repository
#
# This allows the script to work even when it is launched from a directory
# other than the repository root.
# -----------------------------------------------------------------------------

all_arguments <- commandArgs(trailingOnly = FALSE)
script_argument <- grep("^--file=", all_arguments, value = TRUE)

if (length(script_argument) >= 1) {

  script_path <- normalizePath(
    sub("^--file=", "", script_argument[[1]]),
    mustWork = TRUE
  )

  script_dir <- dirname(script_path)

  repo_root <- normalizePath(
    file.path(script_dir, "..", ".."),
    mustWork = TRUE
  )

} else {

  # Fallback for interactive execution.
  repo_root <- normalizePath(
    getwd(),
    mustWork = TRUE
  )
}

# -----------------------------------------------------------------------------
# Input and output paths
# -----------------------------------------------------------------------------

input_file <- if (length(args) >= 2) {

  args[[2]]

} else {

  file.path(
    repo_root,
    "data",
    "clean",
    paste0(project, "_Table_genome_prediction_stats.tsv")
  )
}

output_file <- if (length(args) >= 3) {

  args[[3]]

} else {

  file.path(
    repo_root,
    "data",
    "clean",
    paste0(project, "_percent_genome_annotation.tsv")
  )
}

if (!file.exists(input_file)) {
  stop(
    "Input table not found: ",
    input_file,
    call. = FALSE
  )
}

# -----------------------------------------------------------------------------
# Read and validate the table
# -----------------------------------------------------------------------------

annotation_table <- read.delim(
  input_file,
  header = TRUE,
  sep = "\t",
  quote = "\"",
  comment.char = "",
  check.names = FALSE,
  stringsAsFactors = FALSE
)

region_columns <- c(
  "Exonic",
  "Intronic",
  "UTR",
  "Intergenic"
)

required_columns <- c(
  "Species",
  region_columns
)

missing_columns <- setdiff(
  required_columns,
  colnames(annotation_table)
)

if (length(missing_columns) > 0) {
  stop(
    "The input table is missing required column(s): ",
    paste(missing_columns, collapse = ", "),
    call. = FALSE
  )
}

if (nrow(annotation_table) == 0) {
  stop(
    "The input table contains no samples: ",
    input_file,
    call. = FALSE
  )
}

if (
  any(
    is.na(annotation_table$Species) |
      trimws(annotation_table$Species) == ""
  )
) {
  stop(
    "The Species column contains missing or empty sample names.",
    call. = FALSE
  )
}

if (anyDuplicated(annotation_table$Species) > 0) {

  duplicated_species <- unique(
    annotation_table$Species[
      duplicated(annotation_table$Species)
    ]
  )

  stop(
    "Duplicated sample name(s): ",
    paste(duplicated_species, collapse = ", "),
    call. = FALSE
  )
}

# -----------------------------------------------------------------------------
# Convert genomic-region columns to numeric values
# -----------------------------------------------------------------------------

for (column in region_columns) {

  original_values <- annotation_table[[column]]

  numeric_values <- suppressWarnings(
    as.numeric(original_values)
  )

  invalid_values <- (
    !is.na(original_values) &
      trimws(as.character(original_values)) != "" &
      is.na(numeric_values)
  )

  if (any(invalid_values)) {
    stop(
      "Non-numeric value(s) found in column ",
      column,
      ": ",
      paste(
        unique(original_values[invalid_values]),
        collapse = ", "
      ),
      call. = FALSE
    )
  }

  annotation_table[[column]] <- numeric_values
}

if (
  anyNA(
    annotation_table[
      region_columns
    ]
  )
) {
  stop(
    "Missing values were found in the genomic-region columns.",
    call. = FALSE
  )
}

# -----------------------------------------------------------------------------
# Calculate percentages
#
# Exonic + Intronic + UTR + Intergenic represents the total sequence length
# considered by the genomic-region analysis.
# -----------------------------------------------------------------------------

total_region_length <- rowSums(
  annotation_table[
    region_columns
  ]
)

if (any(total_region_length <= 0)) {

  invalid_species <- annotation_table$Species[
    total_region_length <= 0
  ]

  stop(
    "The total genomic-region length is zero or negative for: ",
    paste(invalid_species, collapse = ", "),
    call. = FALSE
  )
}

percentage_table <- data.frame(
  Species = annotation_table$Species,

  Percent_Exonic = round(
    100 * annotation_table$Exonic / total_region_length,
    digits = 4
  ),

  Percent_Intronic = round(
    100 * annotation_table$Intronic / total_region_length,
    digits = 4
  ),

  Percent_UTR = round(
    100 * annotation_table$UTR / total_region_length,
    digits = 4
  ),

  Percent_Intergenic = round(
    100 * annotation_table$Intergenic / total_region_length,
    digits = 4
  ),

  stringsAsFactors = FALSE
)

# -----------------------------------------------------------------------------
# Save results
# -----------------------------------------------------------------------------

dir.create(
  dirname(output_file),
  recursive = TRUE,
  showWarnings = FALSE
)

write.table(
  percentage_table,
  file = output_file,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE,
  col.names = TRUE
)

message("Samples processed: ", nrow(percentage_table))
message("Results written to: ", output_file)
